#!/bin/bash
set -x
i=0.1
f=0.5
e=100
n=20000
m=120101
g=8
for x in 0 1 2 3 4
do
  t=Train_Dirs/train_dir_i{$i}_f{$f}_e{$e}_n{$n}_m{$m}_x{$x}
  echo python multi_train.py -x "../fold"$x"/" -i $i -f $f -e $e -n $n -m $m  -g $g -t $t ">&" out_{$t}
  python multi_train.py -x "../fold"$x"/" -i $i -f $f -e $e -n $n -m $m  -g $g -t $t >& out_{$t}
done
